apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-seed-production
  namespace: { { .Values.namespace } }
  labels:
    app.kubernetes.io/name: { { .Values.name } }
    app.kubernetes.io/component: db-seed
  annotations:
    'helm.sh/hook': post-install,post-upgrade
    'helm.sh/hook-weight': '-4'
    'helm.sh/hook-delete-policy': before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: seed
          image: { { .Values.api.image } }
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            command: ['sh', '-c', 'npm run db:seed:prod']
          envFrom:
            - secretRef:
                name: foodmission-api-secret
      restartPolicy: Never
