apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodmission-api
  namespace: foodmission
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "warn"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: foodmission-api-hpa
  namespace: foodmission
spec:
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70