  plugins:
    - victoriametrics-metrics-datasource
    - victoriametrics-logs-datasource

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: victoriametrics
          type: victoriametrics-metrics-datasource
          orgId: 1
          access: proxy
          url: http://vmsingle-victoria-metrics-single-server.observability.svc.cluster.local.:8428
          isDefault: true
          
        - name: victoriametrics - cluster
          type: victoriametrics-metrics-datasource
          orgId: 1
          access: proxy
          url: http://vmsingle-victoria-metrics-single-server.observability.svc.cluster.local.:8428
          isDefault: false
        
        - name: victoriatraces
          type: jaeger
          orgId: 1
          access: proxy
          url: http://victoria-traces-vt-single-server.observability.svc.cluster.local:10428/select/jaeger
          isDefault: false

        - name: victorialogs
          type: victoriametrics-logs-datasource
          orgId: 1
          access: proxy
          url: http://victoria-logs-victoria-logs-single-server.observability.svc.cluster.local:9428
          isDefault: false

  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: true
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      victoriametrics:
        gnetId: 10229
        datasource: victoriametrics
      kubernetes:
        gnetId: 14205
        datasource: victoriametrics
