apiVersion: v1
kind: ConfigMap
metadata:
  name: foodmission-config
  namespace: foodmission
  labels:
    app.kubernetes.io/name: foodmission-data-framework
    app.kubernetes.io/component: config
data:
  # Application Configuration
  NODE_ENV: "production"
  PORT: "3000"
  
  # API Configuration
  API_PREFIX: "api/v1"
  API_VERSION: "1.0.0"
  
  # Swagger Configuration
  SWAGGER_ENABLED: "true"
  SWAGGER_PATH: "api/docs"
  
  # Database Configuration
  DATABASE_URL: "postgresql://foodmission:$(DATABASE_PASSWORD)@postgres-service:5432/foodmission?schema=public"
  DATABASE_POOL_SIZE: "10"
  DATABASE_CONNECTION_TIMEOUT: "30000"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_TTL: "3600"
  
  # Keycloak Configuration
  KEYCLOAK_BASE_URL: "http://keycloak-service:8080"
  KEYCLOAK_REALM: "foodmission"
  KEYCLOAK_CLIENT_ID: "foodmission-api"
  
  # OpenFoodFacts Configuration
  OPENFOODFACTS_BASE_URL: "https://world.openfoodfacts.org"
  OPENFOODFACTS_TIMEOUT: "10000"
  OPENFOODFACTS_RETRY_ATTEMPTS: "3"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Health Check Configuration
  HEALTH_CHECK_TIMEOUT: "5000"
  
  # Performance Configuration
  REQUEST_TIMEOUT: "30000"
  BODY_LIMIT: "10mb"
  
  # Security Configuration
  CORS_ENABLED: "true"
  CORS_ORIGIN: "*"
  HELMET_ENABLED: "true"
  
  # Monitoring Configuration
  METRICS_ENABLED: "true"
  METRICS_PATH: "/metrics"