apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: foodmission-api-pdb
  namespace: foodmission
  labels:
    app.kubernetes.io/name: foodmission-data-framework
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: foodmission-data-framework
      app.kubernetes.io/component: api