apiVersion: v1
kind: Service
metadata:
  name: foodmission-api-service
  namespace: foodmission
  labels:
    app.kubernetes.io/name: foodmission-data-framework
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: foodmission-data-framework
    app.kubernetes.io/component: api
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: foodmission-api-headless
  namespace: foodmission
  labels:
    app.kubernetes.io/name: foodmission-data-framework
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: foodmission-data-framework
    app.kubernetes.io/component: api