-- This migration's intent (making foodId nullable and adding foodCategoryId) was
-- incorporated into 20260423122554_add_food_waste_table during the Food→FoodProduct
-- / FoodCategory→GenericFood rename. The food_waste table was created with
-- foodProductId (nullable) and genericFoodId (nullable) directly, so no changes
-- are needed here.
