apiVersion: v1
kind: Secret
metadata:
  name: foodmission-api-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  NODE_ENV: "production"
  DATABASE_URL: "{{ .Values.api.db.url }}"
  SESSION_SECRET: "{{ .Values.api.sessionSecret }}"
  ENCRYPTION_KEY: "{{ .Values.api.encryptionKey }}"
  KEYCLOAK_BASE_URL: "{{ .Values.api.keycloak.baseUrl }}"
  KEYCLOAK_REALM: "{{ .Values.api.keycloak.realm }}"
  KEYCLOAK_CLIENT_ID: "{{ .Values.api.keycloak.clientId }}"
  KEYCLOAK_CLIENT_SECRET: "{{ .Values.api.keycloak.clientSecret }}"
  KEYCLOAK_REDIRECT_URI: "{{ .Values.api.keycloak.redirectUri }}"
  KEYCLOAK_SERVICE_CLIENT_ID: "{{ .Values.api.keycloak.serviceClientId }}"
  KEYCLOAK_SERVICE_CLIENT_SECRET: "{{ .Values.api.keycloak.serviceClientSecret }}"
  # Add other env vars as needed
