apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Values.namespace }}
stringData:
  KC_DB_PASSWORD: "{{ .Values.keycloak.db.password }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.keycloak.admin.password }}"
  # Add other Keycloak secrets here as needed
