apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: {{ .Values.keycloak.image }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        args: ["start"]
        env:
          - name: KC_DB
            value: "postgres"
          - name: KC_DB_URL
            value: "{{ .Values.keycloak.db.url }}"
          - name: KC_DB_USERNAME
            value: "{{ .Values.keycloak.db.username }}"
          - name: KEYCLOAK_ADMIN
            value: "{{ .Values.keycloak.admin.user }}"
          - name: KC_HOSTNAME
            value: "{{ .Values.keycloak.hostname }}"
          - name: KC_PROXY_HEADERS
            value: "xforwarded"
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_PROXY
            value: "edge"
        envFrom:
          - secretRef:
              name: keycloak-secret
        ports:
        - containerPort: 8080
