-- AlterTable
ALTER TABLE "public"."foods" ADD COLUMN     "addedSugars100g" DOUBLE PRECISION,
ADD COLUMN     "allergens" TEXT[],
ADD COLUMN     "brands" TEXT,
ADD COLUMN     "calcium100g" DOUBLE PRECISION,
ADD COLUMN     "carbohydrates100g" DOUBLE PRECISION,
ADD COLUMN     "carbonFootprint" DOUBLE PRECISION,
ADD COLUMN     "categories" TEXT[],
ADD COLUMN     "cholesterol100g" DOUBLE PRECISION,
ADD COLUMN     "completeness" DOUBLE PRECISION,
ADD COLUMN     "countries" TEXT[],
ADD COLUMN     "ecoscoreGrade" TEXT,
ADD COLUMN     "energyKcal100g" DOUBLE PRECISION,
ADD COLUMN     "energyKj100g" DOUBLE PRECISION,
ADD COLUMN     "fat100g" DOUBLE PRECISION,
ADD COLUMN     "fiber100g" DOUBLE PRECISION,
ADD COLUMN     "imageFrontUrl" TEXT,
ADD COLUMN     "imageUrl" TEXT,
ADD COLUMN     "ingredientsAnalysisTags" TEXT[],
ADD COLUMN     "ingredientsText" TEXT,
ADD COLUMN     "iron100g" DOUBLE PRECISION,
ADD COLUMN     "isPalmOilFree" BOOLEAN,
ADD COLUMN     "isVegan" BOOLEAN,
ADD COLUMN     "isVegetarian" BOOLEAN,
ADD COLUMN     "labels" TEXT[],
ADD COLUMN     "magnesium100g" DOUBLE PRECISION,
ADD COLUMN     "manufacturingPlaces" TEXT,
ADD COLUMN     "novaGroup" INTEGER,
ADD COLUMN     "nutrientLevels" JSONB,
ADD COLUMN     "nutrimentsRaw" JSONB,
ADD COLUMN     "nutriscoreGrade" TEXT,
ADD COLUMN     "nutriscoreScore" INTEGER,
ADD COLUMN     "nutritionDataPer" TEXT,
ADD COLUMN     "origins" TEXT,
ADD COLUMN     "packagingMaterials" TEXT[],
ADD COLUMN     "packagingRecycling" TEXT[],
ADD COLUMN     "packagingTags" TEXT[],
ADD COLUMN     "packagingText" TEXT,
ADD COLUMN     "potassium100g" DOUBLE PRECISION,
ADD COLUMN     "proteins100g" DOUBLE PRECISION,
ADD COLUMN     "quantity" TEXT,
ADD COLUMN     "salt100g" DOUBLE PRECISION,
ADD COLUMN     "saturatedFat100g" DOUBLE PRECISION,
ADD COLUMN     "servingSize" TEXT,
ADD COLUMN     "sodium100g" DOUBLE PRECISION,
ADD COLUMN     "sugars100g" DOUBLE PRECISION,
ADD COLUMN     "traces" TEXT[],
ADD COLUMN     "transFat100g" DOUBLE PRECISION,
ADD COLUMN     "vitaminA100g" DOUBLE PRECISION,
ADD COLUMN     "vitaminC100g" DOUBLE PRECISION,
ADD COLUMN     "zinc100g" DOUBLE PRECISION;

-- CreateIndex
CREATE INDEX "foods_nutriscoreGrade_idx" ON "public"."foods"("nutriscoreGrade");

-- CreateIndex
CREATE INDEX "foods_novaGroup_idx" ON "public"."foods"("novaGroup");
